services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: instagram-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: instagram-backend
    env_file:
      - ./.docker.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    container_name: instagram-postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: