# this is for the build stage 
FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm cigit remote -v

COPY . .

RUN npm run build


# ---------- Production Stage ----------
FROM node:20-alpine AS production

WORKDIR /app

COPY package*.json ./

RUN npm ci --omit=dev

COPY --from=builder /app/dist ./dist

USER node

EXPOSE 3000

CMD ["node", "dist/main.js"]